[package]
name = "procedural_macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.77", default-features = false, features = ["full", "parsing", "proc-macro", "derive", "printing"] }
quote = "1.0.37"
proc-macro2 = "1.0.86"
foldhash = "0.1.4"